### PR TITLE
Issue#2-Added additional images and info about the application

### PR DESCRIPTION
**Pull request by rt1301**
Issue#2-I have added the screenshot and information related to addition of new tasks, complete task feature and custom list feature.

### CODE REVIEW

**Review by zippytyro — APPROVED** [review]
Thanks for contributing

**Comment by rt1301** [comment]
On the hacktoberfest, it is showing the repo is invalid for the contest. Can you check and rectify that?

**Comment by zippytyro** [comment]
I've added the labels and topic to the repo @rt1301

**Comment by rt1301** [comment]
Thanks!

**Comment by zippytyro** [comment]
@rt1301 some changes have been made to the rules
[update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Pull request merged**
